# Generated by Django 5.1 on 2024-08-22 01:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remixed_lyrics_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemixLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="remix_level",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="remixed_lyrics_api.remixlevel",
            ),
        ),
    ]
